---
- name: Populate service facts
  service_facts:

- name: Stop and disable resolv service
  service:
    name: systemd-resolved
    enabled: no
    state: stopped
  when: ansible_facts.services['systemd-resolved.service'] is defined

- name: Remove resolv configuration file
  file:
    path: /etc/resolv.conf
    state: absent

- name: Check that powerdns recursor runs
  wait_for: host=127.0.0.1 port=5353 timeout=3

- name: Set DNS
  copy:
    src: files/resolv.conf
    dest: /etc/resolv.conf
    mode: 0644

- name: Configure dnsdist
  template:
    src: dnsdist.conf.j2
    dest: /etc/dnsdist/dnsdist.conf
    mode: 0644
  notify: restart dnsdist

- name: Flush handlers up to this point
  meta: flush_handlers
