---
- name: Copy Let's Encrypt Certs to dnsdist directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0400
    remote_src: yes
  with_items:
    - {
      src: "/root/.acme.sh/{{ DOMAIN }}/fullchain.cer",
      dest: "/etc/dnsdist/fullchain.cer"
      }
    - {
      src: "/root/.acme.sh/{{ DOMAIN }}/{{ DOMAIN }}.key",
      dest: "/etc/dnsdist/{{ DOMAIN }}.key"
    }
