---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://repo.powerdns.com/FD380FBB-pub.asc
    state: present

- name: Add dnsdist repo
  apt_repository:
    repo: deb [arch=amd64] http://repo.powerdns.com/ubuntu {{ dnsdist_ver }} main
    state: present

- name: Install dnsdist packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - dnsdist
    state: present
    update_cache: yes
