---
- name: Remove default configuration file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Make sure conf.d/ exists
  file:
    path: /etc/nginx/conf.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - {
      src: "nginx.conf.j2",
      dest: "/etc/nginx/nginx.conf"
      }
    - {
      src: "default.conf.j2",
      dest: "/etc/nginx/conf.d/default.conf"
      }
    - {
      src: "doh.conf.j2",
      dest: "/etc/nginx/conf.d/doh.conf"
      }
    - {
      src: "dot.conf.j2",
      dest: "/etc/nginx/conf.d/dot.conf"
      }

- name: Check if dhparam exist
  stat:
    path: "/etc/ssl/dhparam.pem"
  register: stat_result

- name: Create dhparam.pem if not exists
  command: |
    openssl dhparam -out /etc/ssl/dhparam.pem 2048
    creates: /etc/ssl/dhparam.pem
  when: not stat_result.stat.exists

- name: Remove nginx access logs if any
  shell: find /var/log/nginx/ -name "*access*" -delete
    # find /var/log/nginx/ -name "*access*" -print0 | xargs --no-run-if-empty -0 rm
  register: rm_result
  changed_when: rm_result.stdout | length > 0