---
- name: restart pdns-recursor
  service:
    name: pdns-recursor
    state: restarted
    enabled: yes

- name: get root hints
  command: /usr/local/bin/get_root_hints.sh

- name: get root dnskeys
  command: /usr/local/bin/get_root_dnskey.sh

