- hosts: libredns
  become: yes
  gather_facts: yes

  vars:
    DOMAIN: "libredns.gr"
    IPv4: "116.202.176.26"
    IPv6: "2a01:4f8:1c0c:8274::1"
    STAGING: "--staging"
    GANDI_LIVEDNS_KEY: ""
    website_repo: "https://gitlab.com/libreops/libredns/libredns.gr.git"

  vars_files:
    - private.yml

  roles:
    - common
    - pdns_recursor
    - acme
    - dnsdist
    - nginx
    - website
    - monitoring
