- hosts: libredns
  become: yes
  gather_facts: yes

  vars:
    DOMAIN: "libredns.gr"
    STATIC: "116.202.176.26"
    STAGING: "--staging"
    GANDI_LIVEDNS_KEY: ""
    website_repo: "https://gitlab.com/libreops/libredns/libredns.gr.git"

  roles:
    - common
    - pdns_recursor
    - acme
    - dnsdist
    - nginx
    - website
