- hosts: libredns
  become: yes
  gather_facts: yes

  vars:
    DOMAIN: "libredns.gr"
    GANDI_LIVEDNS_KEY: ""
    website_repo: "https://gitlab.com/libreops/libredns/libredns.gr.git"
    website_root: "/var/www/libredns.gr/"
    website_bare: "/home/web/libredns.gr.git"

  roles:
    - common
    - pdns-recursor
    - acme
    - dns-over-https
    - dnsdist
    - nginx
    - website
    - ads
