- hosts: libredns
  become: yes
  gather_facts: yes

  vars:
    DOMAIN: "libredns.gr"
    GANDI_LIVEDNS_KEY: ""
    website_repo: "https://gitlab.com/libreops/libredns/libredns.gr.git"

  roles:
    - common
    - pdns-recursor
    - acme
    - dnsdist
    - nginx
    - website
    - ads
