---
- name: Create WildCard Certificate
  shell: |
    /root/.acme.sh/acme.sh --issue --dns dns_gandi_livedns \
      -d {{ DOMAIN }}     \
      -d "*.{{ DOMAIN }}" \
      --dnssleep 300      \
      {{ STAGING | default('', true) }}
  environment:
    GANDI_LIVEDNS_KEY: "{{ GANDI_LIVEDNS_KEY }}"
  register: acme
  failed_when: acme.stderr | length > 0
  changed_when: False
