---
- name: Install Dependencies
  apt:
    pkg:
      - socat
    state: present

- name: Download acme.sh
  get_url:
    url: https://get.acme.sh
    dest: /tmp/acme.sh
    mode: 0750

- name: Install acme.sh
  shell: |
    /tmp/acme.sh
  args:
    creates: "/root/.acme.sh/acme.sh"
