---
- name: Copy PostHook script
  template:
    src: PostHook.sh.j2
    dest: /usr/local/bin/PostHook.sh
    mode: 0750

- name: Ensure PostHook.sh is in acme.sh
  lineinfile:
    path: /root/.acme.sh/{{ DOMAIN }}/{{ DOMAIN }}.conf
    regexp: "^Le_PostHook="
    line: Le_PostHook='/usr/local/bin/PostHook.sh'
