---
- name: Copy Let's Encrypt Certs to dns-over-https directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0400
    remote_src: yes
  with_items:
    - {
      src: "/root/.acme.sh/{{ DOMAIN }}/{{ DOMAIN }}.cer",
      dest: "/etc/dns-over-https/{{ DOMAIN }}.cer"
      }
    - {
      src: "/root/.acme.sh/{{ DOMAIN }}/{{ DOMAIN }}.key",
      dest: "/etc/dns-over-https/{{ DOMAIN }}.key"
    }
