---
- import_tasks: ufw.yml

- name: Get latest version
  shell: |
    curl -sL https://api.github.com/repos/m13253/dns-over-https/tags | jq -r .[0].name | tr -d 'v'
  register: VERSION

- name: Check if dhparam exist
  stat:
    path: "/tmp/doh-server_{{ VERSION.stdout }}_amd64.deb"
  register: stat_result

- name: Download dns-over-https
  get_url:
    url: https://gitlab.com/libreops/libredns/dns-over-https/-/jobs/artifacts/master/raw/doh-server_{{ VERSION.stdout }}_amd64.deb?job=run-build
    dest: /tmp/doh-server_{{ VERSION.stdout }}_amd64.deb
  when: not stat_result.stat.exists

- name: Install dns-over-https
  apt: deb="/tmp/doh-server_{{ VERSION.stdout }}_amd64.deb"

- name: Configure dns-over-https
  template:
    src: doh-server.conf.j2
    dest: /etc/dns-over-https/doh-server.conf

- import_tasks: copy_certs.yml

- name: restart doh
  systemd:
    state: restarted
    daemon_reload: yes
    name: doh-server
