---
- import_tasks: ufw.yml

- import_tasks: install.yml

- import_tasks: config.yml

- import_tasks: copy_certs.yml

- name: restart doh
  systemd:
    state: restarted
    daemon_reload: yes
    name: doh-server
