---
- name: Powerdns Recursor Configuration
  template:
    src: recursor-ads.conf.j2
    dest: /etc/powerdns/recursor-ads.conf
    mode: 0640
    group: pdns

- name: Copy recursor systemd service file
  copy:
    src: /lib/systemd/system/pdns-recursor.service
    dest: /lib/systemd/system/pdns-recursor-ads.service
    mode: 0644
    remote_src: yes

- name: Ensure Powerdns Recursor systemd service file points to ads
  lineinfile:
    path: /lib/systemd/system/pdns-recursor-ads.service
    regexp: "^ExecStart=(.*)"
    line: 'ExecStart=\1 --config-name=ads'
    backrefs: yes

- name: Enable service pdns-recursor-ads, also issue daemon-reload
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: pdns-recursor-ads
