---
- name: restart journald
  service:
    name: systemd-journald
    state: restarted

- name: restart networking
  command: netplan apply

- name: restart systemd-sysctl
  service:
    name: systemd-sysctl
    state: restarted

