---
- name: copy floating config  file to server
  template:
    src: 60-my-floating-ip.cfg.j2
    dest: /etc/network/interfaces.d/60-my-floating-ip.cfg
    mode: 0644
  notify:
    - restart networking
