---
- name: Update all packages on Ubuntu
  apt:
    update_cache: yes
    cache_valid_time: 86400
    upgrade: safe

- name: Install Packages
  apt:
    pkg:
    - ansible
    - certbot
    - figlet
    - jq
    - mlocate
    - socat
    - vim
    state: present
