---
- name: Install Packages
  apt:
    pkg:
    - ansible
    - certbot
    - figlet
    - jq
    - mlocate
    - socat
    - vim
    state: present

- name: Set hostname
  hostname: name={{ inventory_hostname }}

- import_tasks: swap.yml

- import_tasks: journal.yml
