---
- name: Ensure connection tracking module is loaded in boot time
  lineinfile:
    path: /etc/modules
    regexp: "nf_conntrack"
    line: "nf_conntrack"

- name: Copy netfilter connection tracking sysctl settings
  copy:
    src: 99-netfilter.conf
    dest: /etc/sysctl.d/99-netfilter.conf
    mode: "0640"
    owner: root
    group: root
  notify: restart systemd-sysctl
