---
- name: Check if root hints exist
  stat:
    path: "/etc/powerdns/root.hints"
  register: stat_result

- name: Get root hints from closest OpenNic tier-2
  copy:
    src: get_root_hints.sh
    dest: /usr/local/bin/get_root_hints.sh
    mode: 0755
  notify: get root hints

- name: Powerdns Recursor Configuration
  copy:
    src: recursor.conf
    dest: /etc/powerdns/recursor.conf
    mode: 0640
  notify: restart pdns-recursor

- name: Flush handlers up to this point
  meta: flush_handlers
