---
- name: Check if root hints exist
  stat:
    path: "/etc/powerdns/root.hints"
  register: stat_result

- name: Update root hint
  shell: |
    set -o pipefail
    dig . NS @{{ OPENIC_ROOTNS }} | grep -Ev '^;|^$' > /etc/powerdns/root.hints
  args:
    executable: /bin/bash
  when: not stat_result.stat.exists

- name: Powerdns Recursor Configuration
  copy:
    src: recursor.conf
    dest: /etc/powerdns/recursor.conf
    mode: 0640
  notify: restart pdns-recursor

- name: Flush handlers up to this point
  meta: flush_handlers
