---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://repo.powerdns.com/FD380FBB-pub.asc
    state: present

- name: Add PowerDNS Recursor repo
  apt_repository:
    repo: deb [arch=amd64] http://repo.powerdns.com/ubuntu {{ pdns_rec_ver }} main
    state: present

- name: Ansible copy file to remote server
  copy:
    src: apt.pdns
    dest: /etc/apt/preferences.d/pdns
    mode: 0644

- name: Install PowerDNS packages
  apt:
    pkg: pdns-recursor
    state: present
    update_cache: yes
    policy_rc_d: 101
